---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: chef
  log_level: error
  pillars:
    top.sls:
      base:
        '*':
          - chef
    chef.sls:
      chef:
        validation_pem: |
          -----BEGIN RSA PRIVATE KEY-----
          key goes inline here
          -----END RSA PRIVATE KEY-----
        client_rb:
          log_level: info
          local_mode: true
  state_top:
    base:
      '*':
        - chef.install
        - chef.bootstrap

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: ubuntu-14.04
    provisioner:
      salt_install: apt
  - name: ubuntu-16.04
    provisioner:
      salt_install: apt

suites:
  - name: default
